### ISSUE TITLE
gqrx not opening after install

### ISSUE THREAD

**Issue by gr8lite** [alphafox02/focalx_ppa#3]
$ gqrx   (gqrx-sdr_20231130-1_amd64.deb)
gqrx: error while loading shared libraries: libgnuradio-digital.so.3.10.4: cannot open shared object file: No such file or directory

I can not find libgnuradio-digital.so.3.10.4:   I have looked at every search option I came across, but only find earlier or later versions.
I found some information suggesting there may be a typo from the GQRX  calling for it.
Any suggestions how I may resolve this?

(gqrx-sdr_20231130-1_amd64.deb)

**Comment by alphafox02** [comment]
These packages were only meant for DragonOS FocalX. They will not work on anything else. May I ask what you were trying to install it on?

**Comment by gr8lite** [comment]
DragonOS FocalX, update/upgrade to jammy.    Worked perfectly for quite some time.  I tried updating GQRX. Had problems, tried going back to original focalx_ppa.   Can't seem to do anything with any builds from source either.  Seems to install, but errors as mentioned no matter what.   
I can not figure out where that ( libgnuradio-digital.so.3.10.4)  is being called from.
Maybe something isn't purging preventing a clean install?   All the other apps still work fine --Just problem with GQRX

**Comment by gr8lite** [comment]
I think I am making progress downgrading.  Looks like I kept getting upgrade installs until now.  Hopefully this will work (gnuradio 3.08)

**Comment by alphafox02** [comment]
It’s only for GNU Radio 3.10, currently this PPA is mostly for 3.10.4 specifically as built in R35 DragonOS. In DragonOS R36 it is all rebuilt manually around 3.10.10 and that requires a reinstall of the latest DragonOS FocalX ISO. By the way, the name is confusing as FocalX is actually Jammy already. 

Anyways, I’m slowly getting all packages on the PPA setup to only apply to those running R36 or higher.

**Comment by alphafox02** [comment]
libgnuradio-digital.so.3.10.4 Is part of gnuradio. The gnuradio, if messed with, will also mess up gqrx as it uses it under the hood. If things get to far out of whack for you, id grab the latest DragonOS FocalX ISO which has now 3.10.10 Gnuradio at its core. PPA updates will then starts to flow again as I put new ones up.

**Comment by gr8lite** [comment]
okay - I appreciate the information.  
I started trying to restore SRDA..... to get the older version with the DMR demod dsd plugin.
Will we see that again?   I have had no  success with implementing dsdccx in Dragon.
I'm gonna go ahead with Dragon_F36.   If you have any suggestions about getting the digital demod working , I would like to follow up on that as well.  Thanks again for all of your feedback.

**Comment by alphafox02** [comment]
I’ll have to go look, but SDRAngel should still have the DSD portion but maybe I missed it being removed? 

I also include DSDFME in DragonOS that’s located under /usr/src. It works really well when feed audio and setup properly.

**Comment by gr8lite** [comment]
Thank you.  So far 36 looks good.
When in the demod the graphic of the signal remains a large dot which seems
unusual, but it appears the rest seems normal.  Will know better in time.
Thank you for the suggestion.  I was wasting too much time wrestling with
all that stuff.
